language: php
 
services:
  - mysql
 
cache:
  directories:
    - $HOME/.composer/cache
 
# Six versions of PHP...
php:
  - 7.2
 
# ...times five versions of WordPress
env:
  - WP_VERSION=5.7
 
install:
  - composer install --prefer-dist --no-interaction

  # Install the WordPress core test suite
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

 
script:
  - ./vendor/bin/phpunit

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0